spring.application.name=userDemo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#update,create-drop

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://nec-ofc-dbc1:5432/nectar_new
spring.datasource.username=appuser
spring.datasource.password=NecOfc@123
spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.continue-on-error=true
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

